[View in Colaboratory](https://colab.research.google.com/github/SendilCannane/Tensorflow/blob/master/Tensorflow_Softmax.ipynb)

In [8]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

# Create example y_hat.
y_hat = tf.convert_to_tensor(np.array([[0.5, 0.1, 1.5],[2.2, 1.3, 1.7],[0.6, 1.2, 0.4],[2.6, 0.8, 1.7]]))
sess.run(y_hat)

array([[0.5, 0.1, 1.5],
       [2.2, 1.3, 1.7],
       [0.6, 1.2, 0.4],
       [2.6, 0.8, 1.7]])

In [9]:
y_hat_softmax = tf.nn.softmax(y_hat)
sess.run(y_hat_softmax)

array([[0.227863  , 0.15274114, 0.61939586],
       [0.49674623, 0.20196195, 0.30129182],
       [0.27466117, 0.50046528, 0.22487355],
       [0.63618551, 0.10516076, 0.25865373]])

In [10]:
y_pred_cls = tf.argmax(y_hat_softmax, axis=1)
sess.run(y_pred_cls)

array([2, 0, 1, 0])